djangoLessonProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('product.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path

from product import views

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail')
]

product/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django_extensions.db.fields import AutoSlugField
import os


from product.utils import unique_slug_generator, get_product_image_dir_path


class Feature(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=100)
    features = models.ManyToManyField(Feature)

    def __str__(self):
        return self.name


class Product(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=2)
    title = models.CharField(max_length=100)
    in_stock = models.BooleanField(default=True)
    description = models.TextField()
    slug = AutoSlugField(populate_from='title', slugify_function=unique_slug_generator)
    code = models.IntegerField(unique=True)
    date_added = models.DateTimeField(auto_now=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    # mean_rating = models.IntegerField(null=True, blank=True, default=0)
    #
    # def some(self):
    #     revs = self.set_review.all()
    #     ratings = [int(rating) for rating in revs.ratings]
    #     return sum(ratings)/len(ratings)

    def __str__(self):
        return f'{self.title}_{self.code}'


class Review(models.Model):
    RANK_CHOICE = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )

    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    rating = models.CharField(choices=RANK_CHOICE, max_length=1)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    text = models.TextField()
    image = models.ImageField(upload_to='rew_images', null=True, blank=True)


class ProductImage(models.Model):
    image = models.ImageField(upload_to=get_product_image_dir_path)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

product/forms.py
from django import forms

from product import models


class ReviewForm(forms.ModelForm):

    class Meta:
        model = models.Review
        exclude = ('author', 'product', )

product/views.py
from django.shortcuts import render
from django.views import generic
from django.views.generic.edit import FormMixin
from django.views.generic import FormView
from product import models, forms


class ProductListView(generic.ListView):
    model = models.Product
    template_name = 'product_list.html'
    context_object_name = 'products'


class ProductDetailView(FormMixin, generic.DetailView):
    model = models.Product
    template_name = 'product_detail.html'
    context_object_name = 'product'
    form_class = forms.ReviewForm

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['reviews'] = models.Review.objects.filter(product=self.get_object())
        return context

    def post(self, request, slug):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        data = form.cleaned_data
        review = models.Review(**data)

        product = self.get_object()
        author = self.request.user
        review.product = product
        review.author = author

        review.save()
        return super(ProductDetailView, self).form_valid(form)

product/templates/product_detail.html
{% extends 'base.html' %}

{% block content %}
    <img src="{{ product.productimage_set.all.first.image.url }}">

    <p>Name: {{ product.title }}</p>

    <p>Price: {{ product.price }}</p>

    {% if product.in_stock %}
        <H3>In stock!</H3>
    {% else %}
        <h3>Not in stock</h3>
    {% endif %}

    <p>Descr: {{ product.description }}</p>

    <p>Code: {{ product.code }}</p>
    <hr>
    {% for review in reviews %}
        Rating: {{ review.rating }}
        Text: {{ review.text }}
    {% endfor %}
    {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Comment">
        </form>
    {% endif %}

{% endblock %}

product/templates/product_list.html
{%  extends 'base.html' %}

{% block content %}

    {%  for product in products %}
{#        <img src="{{ some_model.image_field.url }}">#}
        <img src="{{ product.productimage_set.all.first.image.url }}" alt="">
        <a href="{% url 'product_detail' product.slug %}">Name: {{ product.title }}</a>
        Price: {{ product.price }}
        {% if product.in_stock %}
            <H3>In stock!</H3>
        {% else %}
            <h3>Not in stock</h3>
        {% endif %}
        <hr>
    {% endfor %}

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>